////
////  AppDelegate.swift
////  Pokedex
////
////  Created by Sean McGovern on 12/9/20.
////  Copyright © 2020 Facebook. All rights reserved.
////

//import UIKit
//
//@UIApplicationMain
//class AppDelegate: UIResponder, UIApplicationDelegate, RCTBridgeDelegate {
//    func sourceURL(for bridge: RCTBridge!) -> URL! {
////        #if DEBUG
//            return RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: "index", fallbackResource:nil)
////        #else
////            return Bundle.main.url(forResource:"main", withExtension:"jsbundle")
////        #endif
//    }
//
//    var window: UIWindow?
//    var bridge: RCTBridge!
//
//    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
//        self.bridge = RCTBridge(delegate: self, launchOptions: launchOptions)
//
//
//        let jsCodeLocation = sourceURL(for: self.bridge)
//        let rootView = RCTRootView(bundleURL:jsCodeLocation!, moduleName: "Pokedex", initialProperties: nil, launchOptions:launchOptions)
////        let rootView = RCTRootView(bridge: self.bridge, moduleName: "Pokedex", initialProperties: nil)
//
//        self.window = UIWindow(frame: UIScreen.main.bounds)
//        let rootViewController = UIViewController()
//
//        rootViewController.view = rootView
//
//        self.window!.rootViewController = rootViewController;
//        self.window!.makeKeyAndVisible()
//
//        return true
//    }
//
//}


//
//import Foundation
//import UIKit
//
//@UIApplicationMain
//class AppDelegate: UIResponder, UIApplicationDelegate {
//  var window: UIWindow?
//  var bridge: RCTBridge!
//
//  func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject : AnyObject]?) -> Bool {
//
//    /**
//     * Loading JavaScript code - uncomment the one you want.
//     *
//     * OPTION 1
//     * Load from development server. Start the server from the repository root:
//     *
//     * $ npm start
//     *
//     * To run on device, change `localhost` to the IP address of your computer
//     * (you can get this by typing `ifconfig` into the terminal and selecting the
//     * `inet` value under `en0:`) and make sure your computer and iOS device are
//     * on the same Wi-Fi network.
//     */
//
//    //var jsCodeLocation = NSURL(string: "http://localhost:8081/index.ios.bundle?platform=ios&dev=true")
//
//
//    /**
//    * OPTION 2
//    * Load from pre-bundled file on disk. The static bundle is automatically
//    * generated by "Bundle React Native code and images" build step.
//    */
//
//    let jsCodeLocation = Bundle.main.url(forResource: "main", withExtension: "jsbundle")
//
//    let rootView = RCTRootView(bundleURL:jsCodeLocation!, moduleName: "Pokedex", initialProperties: nil, launchOptions:launchOptions)
//
//    self.bridge = rootView.bridge
//
//    self.window = UIWindow(frame: UIScreen.main.bounds)
//    let rootViewController = UIViewController()
//
//    rootViewController.view = rootView
//
//    self.window!.rootViewController = rootViewController;
//    self.window!.makeKeyAndVisible()
//
//    return true
//  }
//}

/////////////////////////////////////////////
//import Foundation
//
//import UIKit
//
//@UIApplicationMain
//class AppDelegate: UIResponder, UIApplicationDelegate {
//  var window: UIWindow?
//  var bridge: RCTBridge!
//
//  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
//    //let jsCodeLocation: URL
//
//    //jsCodeLocation = RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: "index.ios", fallbackResource:nil)
//    // let jsCodeLocation: URL
//
//    // jsCodeLocation = RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: "index.ios", fallbackResource:nil)
//    // let jsCodeLocation = Bundle.main.url(forResource: "main", withExtension: "jsbundle")
//    let rootView = RCTRootView(bundleURL: jsCodeLocation, moduleName: "Pokedex", initialProperties: nil, launchOptions: launchOptions)
//    self.bridge = rootView.bridge
//    let rootViewController = UIViewController()
//    rootViewController.view = rootView
//
//    self.window = UIWindow(frame: UIScreen.main.bounds)
//    self.window!.rootViewController = rootViewController
//    self.window!.makeKeyAndVisible()
//
//    return true
//  }
//}
